defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

title: "Artist 2D Canvas Library"
description:
  "Cross platform C++ 2D Canvas Library inspired by the HTML5 canvas API."
url: "https://cycfi.github.io"
baseurl: "/artist"

remote_theme: adobe/hyde-theme@v1.0.0
adobe_hyde:
  header_image: "/assets/images/artist.png"

plugins:
- jemoji

# Using GitHub Jekyll v3.9.0, these are not ignored by default
exclude:
- artist.code-workspace
- Gemfile
- Gemfile.lock
- jekyll.sh
- README.md
